import { genericOAuth } from '@tinyauth/backend/identity-providers/generic-oauth';
import { github } from '@tinyauth/backend/identity-providers/github';
import { google } from '@tinyauth/backend/identity-providers/google';

export function createOauthProviders() {
  return [
    github({
      id: 'github',
      enabled: true,
      display_name: 'GitHub',
      icon_url: 'https://example.com/github.svg',
      client_id: 'test-github-client-id',
      client_secret: 'test-github-client-secret',
      email_conflict_strategy: 'auto_link',
    }),
    google({
      id: 'google',
      enabled: true,
      display_name: 'Google',
      icon_url: 'https://example.com/google.svg',
      client_id: 'test-google-client-id',
      client_secret: 'test-google-client-secret',
      email_conflict_strategy: 'auto_link',
    }),
    github({
      id: 'github-disabled',
      enabled: false,
      display_name: 'GitHub Disabled',
      icon_url: 'https://example.com/github-disabled.svg',
      client_id: 'test-github-disabled-client-id',
      client_secret: 'test-github-disabled-client-secret',
      email_conflict_strategy: 'auto_link',
    }),
  ];
}

export function createMixedOauthProviders(host: string) {
  return [
    genericOAuth({
      id: 'stub-success',
      enabled: true,
      display_name: 'Stub Success',
      icon_url: 'https://example.com/stub-success.svg',
      client_id: 'stub-success-client-id',
      client_secret: 'stub-success-client-secret',
      authorization_url: `${host}/test/oauth-stub/stub-success/authorize`,
      token_url: `${host}/test/oauth-stub/stub-success/token`,
      userinfo_url: `${host}/test/oauth-stub/stub-success/userinfo`,
      scopes: ['openid', 'profile', 'email'],
      email_conflict_strategy: 'auto_link',
      userinfo_mapping: {
        id: 'sub',
        email: 'email',
        email_verified: 'email_verified',
        name: 'name',
        picture: 'picture',
      },
    }),
    genericOAuth({
      id: 'stub-denied',
      enabled: true,
      display_name: 'Stub Denied',
      icon_url: 'https://example.com/stub-denied.svg',
      client_id: 'stub-denied-client-id',
      client_secret: 'stub-denied-client-secret',
      authorization_url: `${host}/test/oauth-stub/stub-denied/authorize`,
      token_url: `${host}/test/oauth-stub/stub-denied/token`,
      userinfo_url: `${host}/test/oauth-stub/stub-denied/userinfo`,
      scopes: ['openid', 'profile', 'email'],
      email_conflict_strategy: 'auto_link',
      userinfo_mapping: {
        id: 'sub',
        email: 'email',
        email_verified: 'email_verified',
        name: 'name',
        picture: 'picture',
      },
    }),
    genericOAuth({
      id: 'stub-not-allowed',
      enabled: true,
      display_name: 'Stub Not Allowed',
      icon_url: 'https://example.com/stub-not-allowed.svg',
      client_id: 'stub-not-allowed-client-id',
      client_secret: 'stub-not-allowed-client-secret',
      authorization_url: `${host}/test/oauth-stub/stub-not-allowed/authorize`,
      token_url: `${host}/test/oauth-stub/stub-not-allowed/token`,
      userinfo_url: `${host}/test/oauth-stub/stub-not-allowed/userinfo`,
      scopes: ['openid', 'profile', 'email'],
      email_conflict_strategy: 'auto_link',
      userinfo_mapping: {
        id: 'sub',
        email: 'email',
        email_verified: 'email_verified',
        name: 'name',
        picture: 'picture',
      },
    }),
    genericOAuth({
      id: 'stub-disabled',
      enabled: false,
      display_name: 'Stub Disabled',
      icon_url: 'https://example.com/stub-disabled.svg',
      client_id: 'stub-disabled-client-id',
      client_secret: 'stub-disabled-client-secret',
      authorization_url: `${host}/test/oauth-stub/stub-disabled/authorize`,
      token_url: `${host}/test/oauth-stub/stub-disabled/token`,
      userinfo_url: `${host}/test/oauth-stub/stub-disabled/userinfo`,
      scopes: ['openid', 'profile', 'email'],
      email_conflict_strategy: 'auto_link',
      userinfo_mapping: {
        id: 'sub',
        email: 'email',
        email_verified: 'email_verified',
        name: 'name',
        picture: 'picture',
      },
    }),
  ];
}

export function createSpecificOauthProviders(host: string) {
  return [
    genericOAuth({
      id: 'github-stub',
      enabled: true,
      display_name: 'GitHub Stub',
      icon_url: 'https://example.com/github-stub.svg',
      client_id: 'github-stub-client-id',
      client_secret: 'github-stub-client-secret',
      authorization_url: `${host}/test/oauth-stub/github-stub/authorize`,
      token_url: `${host}/test/oauth-stub/github-stub/token`,
      userinfo_url: `${host}/test/oauth-stub/github-stub/userinfo`,
      scopes: ['user:email'],
      email_conflict_strategy: 'auto_link',
      userinfo_mapping: {
        id: 'id',
        email: 'email',
        name: 'name',
        picture: 'avatar_url',
      },
    }),
    genericOAuth({
      id: 'apple-stub',
      enabled: true,
      display_name: 'Apple Stub',
      icon_url: 'https://example.com/apple-stub.svg',
      client_id: 'apple-stub-client-id',
      client_secret: 'apple-stub-client-secret',
      authorization_url: `${host}/test/oauth-stub/apple-stub/authorize`,
      token_url: `${host}/test/oauth-stub/apple-stub/token`,
      scopes: ['openid', 'email', 'name'],
      response_mode: 'form_post',
      email_conflict_strategy: 'auto_link',
      userinfo_mapping: {
        id: 'sub',
        email: 'email',
        email_verified: 'email_verified',
      },
    }),
    genericOAuth({
      id: 'google-stub',
      enabled: true,
      display_name: 'Google Stub',
      icon_url: 'https://example.com/google-stub.svg',
      client_id: 'google-stub-client-id',
      client_secret: 'google-stub-client-secret',
      authorization_url: `${host}/test/oauth-stub/google-stub/authorize`,
      token_url: `${host}/test/oauth-stub/google-stub/token`,
      userinfo_url: `${host}/test/oauth-stub/google-stub/userinfo`,
      scopes: ['openid', 'email', 'profile'],
      email_conflict_strategy: 'auto_link',
      userinfo_mapping: {
        id: 'sub',
        email: 'email',
        email_verified: 'email_verified',
        name: 'name',
        picture: 'picture',
      },
    }),
    genericOAuth({
      id: 'apple-denied-stub',
      enabled: true,
      display_name: 'Apple Denied Stub',
      icon_url: 'https://example.com/apple-denied-stub.svg',
      client_id: 'apple-denied-stub-client-id',
      client_secret: 'apple-denied-stub-client-secret',
      authorization_url: `${host}/test/oauth-stub/apple-denied-stub/authorize?scenario=denied`,
      token_url: `${host}/test/oauth-stub/apple-denied-stub/token`,
      scopes: ['openid', 'email', 'name'],
      response_mode: 'form_post',
      email_conflict_strategy: 'auto_link',
      userinfo_mapping: {
        id: 'sub',
        email: 'email',
        email_verified: 'email_verified',
      },
    }),
    genericOAuth({
      id: 'server-error-stub',
      enabled: true,
      display_name: 'Server Error Stub',
      icon_url: 'https://example.com/server-error-stub.svg',
      client_id: 'server-error-stub-client-id',
      client_secret: 'server-error-stub-client-secret',
      authorization_url: `${host}/test/oauth-stub/server-error-stub/authorize?scenario=server_error`,
      token_url: `${host}/test/oauth-stub/server-error-stub/token`,
      userinfo_url: `${host}/test/oauth-stub/server-error-stub/userinfo`,
      scopes: ['openid', 'email', 'profile'],
      email_conflict_strategy: 'auto_link',
      userinfo_mapping: {
        id: 'sub',
        email: 'email',
        email_verified: 'email_verified',
        name: 'name',
        picture: 'picture',
      },
    }),
    genericOAuth({
      id: 'temporarily-unavailable-stub',
      enabled: true,
      display_name: 'Temporarily Unavailable Stub',
      icon_url: 'https://example.com/temporarily-unavailable-stub.svg',
      client_id: 'temporarily-unavailable-stub-client-id',
      client_secret: 'temporarily-unavailable-stub-client-secret',
      authorization_url:
        `${host}/test/oauth-stub/temporarily-unavailable-stub/authorize` +
        '?scenario=temporarily_unavailable',
      token_url: `${host}/test/oauth-stub/temporarily-unavailable-stub/token`,
      userinfo_url: `${host}/test/oauth-stub/temporarily-unavailable-stub/userinfo`,
      scopes: ['openid', 'email', 'profile'],
      email_conflict_strategy: 'auto_link',
      userinfo_mapping: {
        id: 'sub',
        email: 'email',
        email_verified: 'email_verified',
        name: 'name',
        picture: 'picture',
      },
    }),
    genericOAuth({
      id: 'unknown-error-stub',
      enabled: true,
      display_name: 'Unknown Error Stub',
      icon_url: 'https://example.com/unknown-error-stub.svg',
      client_id: 'unknown-error-stub-client-id',
      client_secret: 'unknown-error-stub-client-secret',
      authorization_url: `${host}/test/oauth-stub/unknown-error-stub/authorize?scenario=unknown_error`,
      token_url: `${host}/test/oauth-stub/unknown-error-stub/token`,
      userinfo_url: `${host}/test/oauth-stub/unknown-error-stub/userinfo`,
      scopes: ['openid', 'email', 'profile'],
      email_conflict_strategy: 'auto_link',
      userinfo_mapping: {
        id: 'sub',
        email: 'email',
        email_verified: 'email_verified',
        name: 'name',
        picture: 'picture',
      },
    }),
    genericOAuth({
      id: 'missing-state-stub',
      enabled: true,
      display_name: 'Missing State Stub',
      icon_url: 'https://example.com/missing-state-stub.svg',
      client_id: 'missing-state-stub-client-id',
      client_secret: 'missing-state-stub-client-secret',
      authorization_url: `${host}/test/oauth-stub/missing-state-stub/authorize?scenario=missing_state`,
      token_url: `${host}/test/oauth-stub/missing-state-stub/token`,
      userinfo_url: `${host}/test/oauth-stub/missing-state-stub/userinfo`,
      scopes: ['openid', 'email', 'profile'],
      email_conflict_strategy: 'auto_link',
      userinfo_mapping: {
        id: 'sub',
        email: 'email',
        email_verified: 'email_verified',
        name: 'name',
        picture: 'picture',
      },
    }),
    genericOAuth({
      id: 'missing-code-stub',
      enabled: true,
      display_name: 'Missing Code Stub',
      icon_url: 'https://example.com/missing-code-stub.svg',
      client_id: 'missing-code-stub-client-id',
      client_secret: 'missing-code-stub-client-secret',
      authorization_url: `${host}/test/oauth-stub/missing-code-stub/authorize?scenario=missing_code`,
      token_url: `${host}/test/oauth-stub/missing-code-stub/token`,
      userinfo_url: `${host}/test/oauth-stub/missing-code-stub/userinfo`,
      scopes: ['openid', 'email', 'profile'],
      email_conflict_strategy: 'auto_link',
      userinfo_mapping: {
        id: 'sub',
        email: 'email',
        email_verified: 'email_verified',
        name: 'name',
        picture: 'picture',
      },
    }),
    genericOAuth({
      id: 'token-error-stub',
      enabled: true,
      display_name: 'Token Error Stub',
      icon_url: 'https://example.com/token-error-stub.svg',
      client_id: 'token-error-stub-client-id',
      client_secret: 'token-error-stub-client-secret',
      authorization_url: `${host}/test/oauth-stub/token-error-stub/authorize?scenario=token_error`,
      token_url: `${host}/test/oauth-stub/token-error-stub/token`,
      userinfo_url: `${host}/test/oauth-stub/token-error-stub/userinfo`,
      scopes: ['openid', 'email', 'profile'],
      email_conflict_strategy: 'auto_link',
      userinfo_mapping: {
        id: 'sub',
        email: 'email',
        email_verified: 'email_verified',
        name: 'name',
        picture: 'picture',
      },
    }),
    genericOAuth({
      id: 'userinfo-error-stub',
      enabled: true,
      display_name: 'Userinfo Error Stub',
      icon_url: 'https://example.com/userinfo-error-stub.svg',
      client_id: 'userinfo-error-stub-client-id',
      client_secret: 'userinfo-error-stub-client-secret',
      authorization_url: `${host}/test/oauth-stub/userinfo-error-stub/authorize?scenario=userinfo_error`,
      token_url: `${host}/test/oauth-stub/userinfo-error-stub/token`,
      userinfo_url: `${host}/test/oauth-stub/userinfo-error-stub/userinfo`,
      scopes: ['openid', 'email', 'profile'],
      email_conflict_strategy: 'auto_link',
      userinfo_mapping: {
        id: 'sub',
        email: 'email',
        email_verified: 'email_verified',
        name: 'name',
        picture: 'picture',
      },
    }),
  ];
}
