packages:
  - packages/*
  - examples/clients/*
  - examples/servers/*

catalog:
  "@astrojs/check": ^0.9.9
  "@astrojs/starlight": ^0.39.2
  "@astrojs/starlight-tailwind": ^5.0.0
  "@biomejs/biome": ^2.4.14
  "@hono/node-server": ^2.0.1
  "@hono/standard-validator": ^0.2.2
  "@hookform/resolvers": ^5.2.2
  "@mikro-orm/cli": ^7.0.14
  "@mikro-orm/core": ^7.0.14
  "@mikro-orm/decorators": ^7.0.14
  "@mikro-orm/migrations": ^7.0.14
  "@mikro-orm/postgresql": ^7.0.14
  "@mikro-orm/seeder": ^7.0.14
  "@mikro-orm/sql": ^7.0.14
  "@phosphor-icons/react": ^2.1.10
  "@playwright/test": ^1.59.1
  "@react-email/components": ^1.0.12
  "@react-email/preview-server": ^5.2.10
  "@react-email/render": ^2.0.8
  "@react-email/tailwind": ^2.0.7
  "@rolldown/plugin-babel": ^0.2.3
  "@scalar/astro": ^0.2.14
  "@scalar/hono-api-reference": ^0.10.14
  "@simplewebauthn/browser": ^13.3.0
  "@simplewebauthn/server": ^13.3.0
  "@stricli/core": ^1.2.6
  "@tailwindcss/postcss": 4.2.4
  "@tailwindcss/typography": 0.5.16
  "@tailwindcss/vite": 4.2.4
  "@tanstack/react-query": ^5.100.9
  "@tanstack/react-router": ^1.169.2
  "@tanstack/router-plugin": ^1.167.33
  "@types/node": ^24.12.3
  "@types/nodemailer": ^8.0.0
  "@types/pg": ^8.20.0
  "@types/qrcode": ^1.5.6
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@vitejs/plugin-react": ^5.1.4
  "@vitest/browser-playwright": ^4.1.5
  "@vitest/browser-preview": ^4.1.5
  "@vitest/coverage-v8": ^4.1.5
  "@vitest/ui": ^4.1.5
  astro: ^6.3.1
  babel-plugin-react-compiler: ^1.0.0
  consola: ^3.4.2
  croner: ^10.0.1
  daisyui: ^5.5.19
  dotenv: ^17.4.2
  execa: ^9.6.1
  hono: ^4.12.18
  hono-openapi: ^1.3.0
  i18next: ^26.0.10
  jose: ^6.2.3
  kysely: ^0.28.17
  next: ^16.2.6
  nodemailer: ^8.0.7
  otplib: ^13.4.0
  pg: ^8.20.0
  pino: ^10.3.1
  pino-pretty: ^13.1.3
  qrcode: ^1.5.4
  react: ^19.2.5
  react-dom: ^19.2.5
  react-email: ^6.1.1
  react-hook-form: ^7.75.0
  react-i18next: ^17.0.7
  sharp: ^0.34.5
  tailwindcss: 4.2.4
  tsx: ^4.21.0
  typescript: ^6.0.3
  vite: ^7.2.7
  vitest: ^4.1.5
  vitest-browser-react: ^2.2.0
  wrangler: ^4.90.0
  yaml: ^2.8.4
  zod: ^4.4.3

onlyBuiltDependencies:
  - esbuild
  - libsql
  - sharp
  - workerd
