/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TermsIndexRouteImport } from './routes/terms/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ErrorIndexRouteImport } from './routes/error/index'
import { Route as ConsentIndexRouteImport } from './routes/consent/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as VerifyTotpIndexRouteImport } from './routes/verify/totp/index'
import { Route as VerifyPasskeyIndexRouteImport } from './routes/verify/passkey/index'
import { Route as VerifyEmailIndexRouteImport } from './routes/verify/email/index'
import { Route as Verify2faIndexRouteImport } from './routes/verify/2fa/index'
import { Route as SetupTotpIndexRouteImport } from './routes/setup/totp/index'
import { Route as SetupPasskeyIndexRouteImport } from './routes/setup/passkey/index'
import { Route as Setup2faIndexRouteImport } from './routes/setup/2fa/index'
import { Route as PasswordResetIndexRouteImport } from './routes/password/reset/index'
import { Route as PasswordForgotIndexRouteImport } from './routes/password/forgot/index'
import { Route as LoginPasswordIndexRouteImport } from './routes/login/password/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AccountSelectIndexRouteImport } from './routes/account/select/index'
import { Route as VerifyTotpRecoveryIndexRouteImport } from './routes/verify/totp/recovery/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsIndexRoute = TermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorIndexRoute = ErrorIndexRouteImport.update({
  id: '/error/',
  path: '/error/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentIndexRoute = ConsentIndexRouteImport.update({
  id: '/consent/',
  path: '/consent/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyTotpIndexRoute = VerifyTotpIndexRouteImport.update({
  id: '/verify/totp/',
  path: '/verify/totp/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyPasskeyIndexRoute = VerifyPasskeyIndexRouteImport.update({
  id: '/verify/passkey/',
  path: '/verify/passkey/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailIndexRoute = VerifyEmailIndexRouteImport.update({
  id: '/verify/email/',
  path: '/verify/email/',
  getParentRoute: () => rootRouteImport,
} as any)
const Verify2faIndexRoute = Verify2faIndexRouteImport.update({
  id: '/verify/2fa/',
  path: '/verify/2fa/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupTotpIndexRoute = SetupTotpIndexRouteImport.update({
  id: '/setup/totp/',
  path: '/setup/totp/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupPasskeyIndexRoute = SetupPasskeyIndexRouteImport.update({
  id: '/setup/passkey/',
  path: '/setup/passkey/',
  getParentRoute: () => rootRouteImport,
} as any)
const Setup2faIndexRoute = Setup2faIndexRouteImport.update({
  id: '/setup/2fa/',
  path: '/setup/2fa/',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetIndexRoute = PasswordResetIndexRouteImport.update({
  id: '/password/reset/',
  path: '/password/reset/',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordForgotIndexRoute = PasswordForgotIndexRouteImport.update({
  id: '/password/forgot/',
  path: '/password/forgot/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPasswordIndexRoute = LoginPasswordIndexRouteImport.update({
  id: '/login/password/',
  path: '/login/password/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSelectIndexRoute = AccountSelectIndexRouteImport.update({
  id: '/account/select/',
  path: '/account/select/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyTotpRecoveryIndexRoute = VerifyTotpRecoveryIndexRouteImport.update({
  id: '/verify/totp/recovery/',
  path: '/verify/totp/recovery/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/': typeof AdminIndexRoute
  '/consent/': typeof ConsentIndexRoute
  '/error/': typeof ErrorIndexRoute
  '/login/': typeof LoginIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/account/select/': typeof AccountSelectIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/login/password/': typeof LoginPasswordIndexRoute
  '/password/forgot/': typeof PasswordForgotIndexRoute
  '/password/reset/': typeof PasswordResetIndexRoute
  '/setup/2fa/': typeof Setup2faIndexRoute
  '/setup/passkey/': typeof SetupPasskeyIndexRoute
  '/setup/totp/': typeof SetupTotpIndexRoute
  '/verify/2fa/': typeof Verify2faIndexRoute
  '/verify/email/': typeof VerifyEmailIndexRoute
  '/verify/passkey/': typeof VerifyPasskeyIndexRoute
  '/verify/totp/': typeof VerifyTotpIndexRoute
  '/verify/totp/recovery/': typeof VerifyTotpRecoveryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/consent': typeof ConsentIndexRoute
  '/error': typeof ErrorIndexRoute
  '/login': typeof LoginIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/register': typeof RegisterIndexRoute
  '/terms': typeof TermsIndexRoute
  '/account/select': typeof AccountSelectIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/login/password': typeof LoginPasswordIndexRoute
  '/password/forgot': typeof PasswordForgotIndexRoute
  '/password/reset': typeof PasswordResetIndexRoute
  '/setup/2fa': typeof Setup2faIndexRoute
  '/setup/passkey': typeof SetupPasskeyIndexRoute
  '/setup/totp': typeof SetupTotpIndexRoute
  '/verify/2fa': typeof Verify2faIndexRoute
  '/verify/email': typeof VerifyEmailIndexRoute
  '/verify/passkey': typeof VerifyPasskeyIndexRoute
  '/verify/totp': typeof VerifyTotpIndexRoute
  '/verify/totp/recovery': typeof VerifyTotpRecoveryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/': typeof AdminIndexRoute
  '/consent/': typeof ConsentIndexRoute
  '/error/': typeof ErrorIndexRoute
  '/login/': typeof LoginIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/account/select/': typeof AccountSelectIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/login/password/': typeof LoginPasswordIndexRoute
  '/password/forgot/': typeof PasswordForgotIndexRoute
  '/password/reset/': typeof PasswordResetIndexRoute
  '/setup/2fa/': typeof Setup2faIndexRoute
  '/setup/passkey/': typeof SetupPasskeyIndexRoute
  '/setup/totp/': typeof SetupTotpIndexRoute
  '/verify/2fa/': typeof Verify2faIndexRoute
  '/verify/email/': typeof VerifyEmailIndexRoute
  '/verify/passkey/': typeof VerifyPasskeyIndexRoute
  '/verify/totp/': typeof VerifyTotpIndexRoute
  '/verify/totp/recovery/': typeof VerifyTotpRecoveryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/'
    | '/consent/'
    | '/error/'
    | '/login/'
    | '/profile/'
    | '/register/'
    | '/terms/'
    | '/account/select/'
    | '/admin/users/'
    | '/login/password/'
    | '/password/forgot/'
    | '/password/reset/'
    | '/setup/2fa/'
    | '/setup/passkey/'
    | '/setup/totp/'
    | '/verify/2fa/'
    | '/verify/email/'
    | '/verify/passkey/'
    | '/verify/totp/'
    | '/verify/totp/recovery/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/consent'
    | '/error'
    | '/login'
    | '/profile'
    | '/register'
    | '/terms'
    | '/account/select'
    | '/admin/users'
    | '/login/password'
    | '/password/forgot'
    | '/password/reset'
    | '/setup/2fa'
    | '/setup/passkey'
    | '/setup/totp'
    | '/verify/2fa'
    | '/verify/email'
    | '/verify/passkey'
    | '/verify/totp'
    | '/verify/totp/recovery'
  id:
    | '__root__'
    | '/'
    | '/admin/'
    | '/consent/'
    | '/error/'
    | '/login/'
    | '/profile/'
    | '/register/'
    | '/terms/'
    | '/account/select/'
    | '/admin/users/'
    | '/login/password/'
    | '/password/forgot/'
    | '/password/reset/'
    | '/setup/2fa/'
    | '/setup/passkey/'
    | '/setup/totp/'
    | '/verify/2fa/'
    | '/verify/email/'
    | '/verify/passkey/'
    | '/verify/totp/'
    | '/verify/totp/recovery/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ConsentIndexRoute: typeof ConsentIndexRoute
  ErrorIndexRoute: typeof ErrorIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  TermsIndexRoute: typeof TermsIndexRoute
  AccountSelectIndexRoute: typeof AccountSelectIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  LoginPasswordIndexRoute: typeof LoginPasswordIndexRoute
  PasswordForgotIndexRoute: typeof PasswordForgotIndexRoute
  PasswordResetIndexRoute: typeof PasswordResetIndexRoute
  Setup2faIndexRoute: typeof Setup2faIndexRoute
  SetupPasskeyIndexRoute: typeof SetupPasskeyIndexRoute
  SetupTotpIndexRoute: typeof SetupTotpIndexRoute
  Verify2faIndexRoute: typeof Verify2faIndexRoute
  VerifyEmailIndexRoute: typeof VerifyEmailIndexRoute
  VerifyPasskeyIndexRoute: typeof VerifyPasskeyIndexRoute
  VerifyTotpIndexRoute: typeof VerifyTotpIndexRoute
  VerifyTotpRecoveryIndexRoute: typeof VerifyTotpRecoveryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/': {
      id: '/terms/'
      path: '/terms'
      fullPath: '/terms/'
      preLoaderRoute: typeof TermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/': {
      id: '/error/'
      path: '/error'
      fullPath: '/error/'
      preLoaderRoute: typeof ErrorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent/': {
      id: '/consent/'
      path: '/consent'
      fullPath: '/consent/'
      preLoaderRoute: typeof ConsentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/totp/': {
      id: '/verify/totp/'
      path: '/verify/totp'
      fullPath: '/verify/totp/'
      preLoaderRoute: typeof VerifyTotpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/passkey/': {
      id: '/verify/passkey/'
      path: '/verify/passkey'
      fullPath: '/verify/passkey/'
      preLoaderRoute: typeof VerifyPasskeyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/email/': {
      id: '/verify/email/'
      path: '/verify/email'
      fullPath: '/verify/email/'
      preLoaderRoute: typeof VerifyEmailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/2fa/': {
      id: '/verify/2fa/'
      path: '/verify/2fa'
      fullPath: '/verify/2fa/'
      preLoaderRoute: typeof Verify2faIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/totp/': {
      id: '/setup/totp/'
      path: '/setup/totp'
      fullPath: '/setup/totp/'
      preLoaderRoute: typeof SetupTotpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/passkey/': {
      id: '/setup/passkey/'
      path: '/setup/passkey'
      fullPath: '/setup/passkey/'
      preLoaderRoute: typeof SetupPasskeyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/2fa/': {
      id: '/setup/2fa/'
      path: '/setup/2fa'
      fullPath: '/setup/2fa/'
      preLoaderRoute: typeof Setup2faIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password/reset/': {
      id: '/password/reset/'
      path: '/password/reset'
      fullPath: '/password/reset/'
      preLoaderRoute: typeof PasswordResetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password/forgot/': {
      id: '/password/forgot/'
      path: '/password/forgot'
      fullPath: '/password/forgot/'
      preLoaderRoute: typeof PasswordForgotIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/password/': {
      id: '/login/password/'
      path: '/login/password'
      fullPath: '/login/password/'
      preLoaderRoute: typeof LoginPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/select/': {
      id: '/account/select/'
      path: '/account/select'
      fullPath: '/account/select/'
      preLoaderRoute: typeof AccountSelectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/totp/recovery/': {
      id: '/verify/totp/recovery/'
      path: '/verify/totp/recovery'
      fullPath: '/verify/totp/recovery/'
      preLoaderRoute: typeof VerifyTotpRecoveryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  ConsentIndexRoute: ConsentIndexRoute,
  ErrorIndexRoute: ErrorIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  TermsIndexRoute: TermsIndexRoute,
  AccountSelectIndexRoute: AccountSelectIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  LoginPasswordIndexRoute: LoginPasswordIndexRoute,
  PasswordForgotIndexRoute: PasswordForgotIndexRoute,
  PasswordResetIndexRoute: PasswordResetIndexRoute,
  Setup2faIndexRoute: Setup2faIndexRoute,
  SetupPasskeyIndexRoute: SetupPasskeyIndexRoute,
  SetupTotpIndexRoute: SetupTotpIndexRoute,
  Verify2faIndexRoute: Verify2faIndexRoute,
  VerifyEmailIndexRoute: VerifyEmailIndexRoute,
  VerifyPasskeyIndexRoute: VerifyPasskeyIndexRoute,
  VerifyTotpIndexRoute: VerifyTotpIndexRoute,
  VerifyTotpRecoveryIndexRoute: VerifyTotpRecoveryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
