/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyTotpIndexRouteImport } from './routes/verify-totp/index'
import { Route as VerifyPasskeyIndexRouteImport } from './routes/verify-passkey/index'
import { Route as VerifyEmailIndexRouteImport } from './routes/verify-email/index'
import { Route as Verify2faIndexRouteImport } from './routes/verify-2fa/index'
import { Route as SetupTotpIndexRouteImport } from './routes/setup-totp/index'
import { Route as ResetPasswordIndexRouteImport } from './routes/reset-password/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ForgotPasswordIndexRouteImport } from './routes/forgot-password/index'
import { Route as ErrorIndexRouteImport } from './routes/error/index'
import { Route as ConsentIndexRouteImport } from './routes/consent/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyTotpIndexRoute = VerifyTotpIndexRouteImport.update({
  id: '/verify-totp/',
  path: '/verify-totp/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyPasskeyIndexRoute = VerifyPasskeyIndexRouteImport.update({
  id: '/verify-passkey/',
  path: '/verify-passkey/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailIndexRoute = VerifyEmailIndexRouteImport.update({
  id: '/verify-email/',
  path: '/verify-email/',
  getParentRoute: () => rootRouteImport,
} as any)
const Verify2faIndexRoute = Verify2faIndexRouteImport.update({
  id: '/verify-2fa/',
  path: '/verify-2fa/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupTotpIndexRoute = SetupTotpIndexRouteImport.update({
  id: '/setup-totp/',
  path: '/setup-totp/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordIndexRoute = ResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordIndexRoute = ForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorIndexRoute = ErrorIndexRouteImport.update({
  id: '/error/',
  path: '/error/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentIndexRoute = ConsentIndexRouteImport.update({
  id: '/consent/',
  path: '/consent/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consent': typeof ConsentIndexRoute
  '/error': typeof ErrorIndexRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/login': typeof LoginIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/register': typeof RegisterIndexRoute
  '/reset-password': typeof ResetPasswordIndexRoute
  '/setup-totp': typeof SetupTotpIndexRoute
  '/verify-2fa': typeof Verify2faIndexRoute
  '/verify-email': typeof VerifyEmailIndexRoute
  '/verify-passkey': typeof VerifyPasskeyIndexRoute
  '/verify-totp': typeof VerifyTotpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consent': typeof ConsentIndexRoute
  '/error': typeof ErrorIndexRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/login': typeof LoginIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/register': typeof RegisterIndexRoute
  '/reset-password': typeof ResetPasswordIndexRoute
  '/setup-totp': typeof SetupTotpIndexRoute
  '/verify-2fa': typeof Verify2faIndexRoute
  '/verify-email': typeof VerifyEmailIndexRoute
  '/verify-passkey': typeof VerifyPasskeyIndexRoute
  '/verify-totp': typeof VerifyTotpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consent/': typeof ConsentIndexRoute
  '/error/': typeof ErrorIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/login/': typeof LoginIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/setup-totp/': typeof SetupTotpIndexRoute
  '/verify-2fa/': typeof Verify2faIndexRoute
  '/verify-email/': typeof VerifyEmailIndexRoute
  '/verify-passkey/': typeof VerifyPasskeyIndexRoute
  '/verify-totp/': typeof VerifyTotpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consent'
    | '/error'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/setup-totp'
    | '/verify-2fa'
    | '/verify-email'
    | '/verify-passkey'
    | '/verify-totp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consent'
    | '/error'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/setup-totp'
    | '/verify-2fa'
    | '/verify-email'
    | '/verify-passkey'
    | '/verify-totp'
  id:
    | '__root__'
    | '/'
    | '/consent/'
    | '/error/'
    | '/forgot-password/'
    | '/login/'
    | '/profile/'
    | '/register/'
    | '/reset-password/'
    | '/setup-totp/'
    | '/verify-2fa/'
    | '/verify-email/'
    | '/verify-passkey/'
    | '/verify-totp/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsentIndexRoute: typeof ConsentIndexRoute
  ErrorIndexRoute: typeof ErrorIndexRoute
  ForgotPasswordIndexRoute: typeof ForgotPasswordIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  ResetPasswordIndexRoute: typeof ResetPasswordIndexRoute
  SetupTotpIndexRoute: typeof SetupTotpIndexRoute
  Verify2faIndexRoute: typeof Verify2faIndexRoute
  VerifyEmailIndexRoute: typeof VerifyEmailIndexRoute
  VerifyPasskeyIndexRoute: typeof VerifyPasskeyIndexRoute
  VerifyTotpIndexRoute: typeof VerifyTotpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-totp/': {
      id: '/verify-totp/'
      path: '/verify-totp'
      fullPath: '/verify-totp'
      preLoaderRoute: typeof VerifyTotpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-passkey/': {
      id: '/verify-passkey/'
      path: '/verify-passkey'
      fullPath: '/verify-passkey'
      preLoaderRoute: typeof VerifyPasskeyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email/': {
      id: '/verify-email/'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-2fa/': {
      id: '/verify-2fa/'
      path: '/verify-2fa'
      fullPath: '/verify-2fa'
      preLoaderRoute: typeof Verify2faIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-totp/': {
      id: '/setup-totp/'
      path: '/setup-totp'
      fullPath: '/setup-totp'
      preLoaderRoute: typeof SetupTotpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/': {
      id: '/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password/': {
      id: '/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/': {
      id: '/error/'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent/': {
      id: '/consent/'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsentIndexRoute: ConsentIndexRoute,
  ErrorIndexRoute: ErrorIndexRoute,
  ForgotPasswordIndexRoute: ForgotPasswordIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  ResetPasswordIndexRoute: ResetPasswordIndexRoute,
  SetupTotpIndexRoute: SetupTotpIndexRoute,
  Verify2faIndexRoute: Verify2faIndexRoute,
  VerifyEmailIndexRoute: VerifyEmailIndexRoute,
  VerifyPasskeyIndexRoute: VerifyPasskeyIndexRoute,
  VerifyTotpIndexRoute: VerifyTotpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
