services:
  issuary:
    image: tinyrack-net/issuary
    build:
      context: ../..
      dockerfile: packages/standalone/Dockerfile
    init: true
    ports:
      - "8080:8080"
    volumes:
      - ./config.dev.yaml:/config/config.dev.yaml:ro
      - issuary-data:/opt/issuary/data

volumes:
  issuary-data:
