services:
  tinyauth:
    image: tinyrack-net/tinyauth
    build:
      context: ../..
      dockerfile: packages/standalone/Dockerfile
    init: true
    ports:
      - "8080:8080"
    volumes:
      - ./config.dev.yaml:/config/config.dev.yaml:ro
      - tinyauth-data:/opt/tinyauth/data

volumes:
  tinyauth-data:
