app:
  host: http://localhost:8080
  port: 8080
  cookie_secret: 3e8a82a5d70bc32809c1757e06c3cccbc32f14dbbbded8d494983099cd84a92b
  jwt_access_token_ttl: 3600
  jwt_refresh_token_ttl: 2592000
  public_registration: true
  supported_languages:
    - ko
    - en
    - ja
  default_language: auto
  fallback_language: ko
admin:
  enabled: true
  port: !env ADMIN_PORT

database:
  type: memory

smtp:
  test: true

authentication_methods:
  password:
    type: password
    enabled: true
    totp:
      enabled: false
      required: false
    passkey:
      enabled: false
      required: false
  google:
    type: oauth
    enabled: true
    provider: google
    display_name: Google
    client_id: test-google-client-id
    client_secret: test-google-client-secret
    email_conflict_strategy: auto_link
  github:
    type: oauth
    enabled: false
    provider: github
    display_name: GitHub
    client_id: test-github-client-id
    client_secret: test-github-client-secret
    email_conflict_strategy: auto_link

providers:
  - id: test-config-oauth-client
    name: My App
    logo_uri: https://myapp.com/auth/callback
    client_id: sdlk3n3dkj2
    client_secret: sdlk3n3dkj2
    redirect_uris:
      - http://localhost:8080/callback
    response_types:
      - code
    grant_types:
      - authorization_code
    scope: openid profile email id_token

users:
  - id: test-config-user
    email: test-config-user@example.com
    password: changemelater
    role: admin
    totp_secret: sdlk3n3dkj2laksdjflaksdjf3
    totp_backup_codes:
      - sdlk3n3dkj2alksdjflaksdjf3
