app:
  host: http://localhost:8080
  port: 8080
  cookie_secret: 3e8a82a5d70bc32809c1757e06c3cccbc32f14dbbbded8d494983099cd84a92b
  jwt_access_token_ttl: 3600
  jwt_refresh_token_ttl: 2592000
  public_registration: true
  supported_languages:
    - ko
    - en
    - ja
  default_language: auto
  fallback_language: ko
  light_theme: light
  dark_theme: dark
  theme_mode: system

admin:
  enabled: true
  port: !env ADMIN_PORT

database:
  type: sqlite
  path: test.db
  # type: postgres
  # host: !env DATABASE_URL
  # port: !env DATABASE_PORT
  # name: !env DATABASE_NAME
  # user: !env DATABASE_USER
  # password: !env DATABASE_PASSWORD

smtp:
  host: mail.winetree94.com
  secure: true
  port: 465
  user: "tester@tinyrack.net"
  password: !env SMTP_PASSWORD
  from: "tester@tinyrack.net"
  test: false

authentication_methods:
  password:
    type: password
    enabled: false
    email_verification: true
    totp:
      enabled: false
      required: false
    passkey:
      enabled: false
      required: false
  github:
    type: oauth
    enabled: true
    provider: github
    display_name: GitHub
    client_id: !env GITHUB_CLIENT_ID
    client_secret: !env GITHUB_CLIENT_SECRET
    email_conflict_strategy: auto_link
  # google:
  #   type: oauth
  #   enabled: false
  #   provider: google
  #   display_name: Google
  #   client_id: !env GOOGLE_CLIENT_ID
  #   client_secret: !env GOOGLE_CLIENT_SECRET
  #   email_conflict_strategy: auto_link

providers:
  - id: test-config-oauth-client
    name: OIDC Test Client
    logo_uri: http://localhost:3000
    client_id: sdlk3n3dkj2
    client_secret: sdlk3n3dkj2
    redirect_uris:
      - http://localhost:3000/api/callback
    response_types:
      - code
    grant_types:
      - authorization_code
      - refresh_token
    scope: openid profile email

users:
  - id: test-config-user
    email: test-config-user@example.com
    password: changemelater
    role: admin
    totp_secret: sdlk3n3dkj2laksdjflaksdjf3
    totp_backup_codes:
      - sdlk3n3dkj2alksdjflaksdjf3
