import type { AppConfigInput } from '@tinyauth/backend/app';
import {
  E2E_TEST_CLIENT_CONFIG,
  E2E_TEST_USER_CONFIG,
} from '#frontend-e2e/fixtures/index.js';

/**
 * Creates a config with provider-specific OAuth stubs for e2e tests.
 * Uses generic_oauth type to point at local stub endpoints that mimic
 * real provider behaviors (GitHub field mapping, Apple form_post + ID token,
 * Google standard OIDC).
 */
export function createOauthProvidersSpecificConfig(
  backendPort: number,
  frontendPort: number,
): AppConfigInput {
  const host = `http://localhost:${backendPort}`;

  return {
    app: {
      host,
      port: backendPort,
      cookie_secret:
        '88d4e6f8a0b2c4d6e8f0112233445566778899aabbccddeeff00112233445566',
      allowed_signup_emails: ['*@allowed.test'],
      supported_languages: ['en'],
      default_language: 'en',
      fallback_language: 'en',
      frontend: {
        enabled: true,
        mode: 'proxy',
        path: `http://localhost:${frontendPort}`,
      },
    },
    identity_providers: [
      {
        id: 'github-stub',
        type: 'generic_oauth',
        enabled: true,
        display_name: 'GitHub Stub',
        icon_url: 'https://example.com/github-stub.svg',
        client_id: 'github-stub-client-id',
        client_secret: 'github-stub-client-secret',
        authorization_url: `${host}/test/oauth-stub/github-stub/authorize`,
        token_url: `${host}/test/oauth-stub/github-stub/token`,
        userinfo_url: `${host}/test/oauth-stub/github-stub/userinfo`,
        scopes: ['user:email'],
        email_conflict_strategy: 'auto_link',
        userinfo_mapping: {
          id: 'id',
          email: 'email',
          name: 'name',
          picture: 'avatar_url',
        },
      },
      {
        id: 'apple-stub',
        type: 'generic_oauth',
        enabled: true,
        display_name: 'Apple Stub',
        icon_url: 'https://example.com/apple-stub.svg',
        client_id: 'apple-stub-client-id',
        client_secret: 'apple-stub-client-secret',
        authorization_url: `${host}/test/oauth-stub/apple-stub/authorize`,
        token_url: `${host}/test/oauth-stub/apple-stub/token`,
        scopes: ['openid', 'email', 'name'],
        response_mode: 'form_post',
        email_conflict_strategy: 'auto_link',
        userinfo_mapping: {
          id: 'sub',
          email: 'email',
          email_verified: 'email_verified',
        },
      },
      {
        id: 'google-stub',
        type: 'generic_oauth',
        enabled: true,
        display_name: 'Google Stub',
        icon_url: 'https://example.com/google-stub.svg',
        client_id: 'google-stub-client-id',
        client_secret: 'google-stub-client-secret',
        authorization_url: `${host}/test/oauth-stub/google-stub/authorize`,
        token_url: `${host}/test/oauth-stub/google-stub/token`,
        userinfo_url: `${host}/test/oauth-stub/google-stub/userinfo`,
        scopes: ['openid', 'email', 'profile'],
        email_conflict_strategy: 'auto_link',
        userinfo_mapping: {
          id: 'sub',
          email: 'email',
          email_verified: 'email_verified',
          name: 'name',
          picture: 'picture',
        },
      },
      {
        id: 'apple-denied-stub',
        type: 'generic_oauth',
        enabled: true,
        display_name: 'Apple Denied Stub',
        icon_url: 'https://example.com/apple-denied-stub.svg',
        client_id: 'apple-denied-stub-client-id',
        client_secret: 'apple-denied-stub-client-secret',
        authorization_url: `${host}/test/oauth-stub/apple-denied-stub/authorize?scenario=denied`,
        token_url: `${host}/test/oauth-stub/apple-denied-stub/token`,
        scopes: ['openid', 'email', 'name'],
        response_mode: 'form_post',
        email_conflict_strategy: 'auto_link',
        userinfo_mapping: {
          id: 'sub',
          email: 'email',
          email_verified: 'email_verified',
        },
      },
      {
        id: 'server-error-stub',
        type: 'generic_oauth',
        enabled: true,
        display_name: 'Server Error Stub',
        icon_url: 'https://example.com/server-error-stub.svg',
        client_id: 'server-error-stub-client-id',
        client_secret: 'server-error-stub-client-secret',
        authorization_url: `${host}/test/oauth-stub/server-error-stub/authorize?scenario=server_error`,
        token_url: `${host}/test/oauth-stub/server-error-stub/token`,
        userinfo_url: `${host}/test/oauth-stub/server-error-stub/userinfo`,
        scopes: ['openid', 'email', 'profile'],
        email_conflict_strategy: 'auto_link',
        userinfo_mapping: {
          id: 'sub',
          email: 'email',
          email_verified: 'email_verified',
          name: 'name',
          picture: 'picture',
        },
      },
      {
        id: 'temporarily-unavailable-stub',
        type: 'generic_oauth',
        enabled: true,
        display_name: 'Temporarily Unavailable Stub',
        icon_url: 'https://example.com/temporarily-unavailable-stub.svg',
        client_id: 'temporarily-unavailable-stub-client-id',
        client_secret: 'temporarily-unavailable-stub-client-secret',
        authorization_url: `${host}/test/oauth-stub/temporarily-unavailable-stub/authorize?scenario=temporarily_unavailable`,
        token_url: `${host}/test/oauth-stub/temporarily-unavailable-stub/token`,
        userinfo_url: `${host}/test/oauth-stub/temporarily-unavailable-stub/userinfo`,
        scopes: ['openid', 'email', 'profile'],
        email_conflict_strategy: 'auto_link',
        userinfo_mapping: {
          id: 'sub',
          email: 'email',
          email_verified: 'email_verified',
          name: 'name',
          picture: 'picture',
        },
      },
      {
        id: 'unknown-error-stub',
        type: 'generic_oauth',
        enabled: true,
        display_name: 'Unknown Error Stub',
        icon_url: 'https://example.com/unknown-error-stub.svg',
        client_id: 'unknown-error-stub-client-id',
        client_secret: 'unknown-error-stub-client-secret',
        authorization_url: `${host}/test/oauth-stub/unknown-error-stub/authorize?scenario=unknown_error`,
        token_url: `${host}/test/oauth-stub/unknown-error-stub/token`,
        userinfo_url: `${host}/test/oauth-stub/unknown-error-stub/userinfo`,
        scopes: ['openid', 'email', 'profile'],
        email_conflict_strategy: 'auto_link',
        userinfo_mapping: {
          id: 'sub',
          email: 'email',
          email_verified: 'email_verified',
          name: 'name',
          picture: 'picture',
        },
      },
      {
        id: 'missing-state-stub',
        type: 'generic_oauth',
        enabled: true,
        display_name: 'Missing State Stub',
        icon_url: 'https://example.com/missing-state-stub.svg',
        client_id: 'missing-state-stub-client-id',
        client_secret: 'missing-state-stub-client-secret',
        authorization_url: `${host}/test/oauth-stub/missing-state-stub/authorize?scenario=missing_state`,
        token_url: `${host}/test/oauth-stub/missing-state-stub/token`,
        userinfo_url: `${host}/test/oauth-stub/missing-state-stub/userinfo`,
        scopes: ['openid', 'email', 'profile'],
        email_conflict_strategy: 'auto_link',
        userinfo_mapping: {
          id: 'sub',
          email: 'email',
          email_verified: 'email_verified',
          name: 'name',
          picture: 'picture',
        },
      },
      {
        id: 'missing-code-stub',
        type: 'generic_oauth',
        enabled: true,
        display_name: 'Missing Code Stub',
        icon_url: 'https://example.com/missing-code-stub.svg',
        client_id: 'missing-code-stub-client-id',
        client_secret: 'missing-code-stub-client-secret',
        authorization_url: `${host}/test/oauth-stub/missing-code-stub/authorize?scenario=missing_code`,
        token_url: `${host}/test/oauth-stub/missing-code-stub/token`,
        userinfo_url: `${host}/test/oauth-stub/missing-code-stub/userinfo`,
        scopes: ['openid', 'email', 'profile'],
        email_conflict_strategy: 'auto_link',
        userinfo_mapping: {
          id: 'sub',
          email: 'email',
          email_verified: 'email_verified',
          name: 'name',
          picture: 'picture',
        },
      },
      {
        id: 'token-error-stub',
        type: 'generic_oauth',
        enabled: true,
        display_name: 'Token Error Stub',
        icon_url: 'https://example.com/token-error-stub.svg',
        client_id: 'token-error-stub-client-id',
        client_secret: 'token-error-stub-client-secret',
        authorization_url: `${host}/test/oauth-stub/token-error-stub/authorize?scenario=token_error`,
        token_url: `${host}/test/oauth-stub/token-error-stub/token`,
        userinfo_url: `${host}/test/oauth-stub/token-error-stub/userinfo`,
        scopes: ['openid', 'email', 'profile'],
        email_conflict_strategy: 'auto_link',
        userinfo_mapping: {
          id: 'sub',
          email: 'email',
          email_verified: 'email_verified',
          name: 'name',
          picture: 'picture',
        },
      },
      {
        id: 'userinfo-error-stub',
        type: 'generic_oauth',
        enabled: true,
        display_name: 'Userinfo Error Stub',
        icon_url: 'https://example.com/userinfo-error-stub.svg',
        client_id: 'userinfo-error-stub-client-id',
        client_secret: 'userinfo-error-stub-client-secret',
        authorization_url: `${host}/test/oauth-stub/userinfo-error-stub/authorize?scenario=userinfo_error`,
        token_url: `${host}/test/oauth-stub/userinfo-error-stub/token`,
        userinfo_url: `${host}/test/oauth-stub/userinfo-error-stub/userinfo`,
        scopes: ['openid', 'email', 'profile'],
        email_conflict_strategy: 'auto_link',
        userinfo_mapping: {
          id: 'sub',
          email: 'email',
          email_verified: 'email_verified',
          name: 'name',
          picture: 'picture',
        },
      },
    ],
    logging: {
      level: 'silent',
      format: 'json',
    },
    database: {
      type: 'memory',
    },
    users: [E2E_TEST_USER_CONFIG],
    clients: [E2E_TEST_CLIENT_CONFIG],
  };
}
